blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('blog/', views.blog_list, name='blog_list'),
    path('blog/<slug:slug>/', views.post_detail, name='post_detail'),
]

boycott/urls.py
# boycott/urls.py
from django.urls import path
from .views import BoycottListView, BoycottDetailView, submit_report

app_name = 'boycott'

urlpatterns = [
    path('', BoycottListView.as_view(), name='boycott-list'),  # Changed from 'boycott/'
    path('category/<int:pk>/', BoycottListView.as_view(), name='boycott-category'),
    path('target/<int:pk>/', BoycottDetailView.as_view(), name='boycott-detail'),
    path('report/<int:pk>/', submit_report, name='submit-report'),
]

causes/urls.py
from django.urls import path
from . import views

app_name = 'causes'

urlpatterns = [
    path('causes/', views.cause_list, name='cause_list'),
    path('causes/<slug:slug>/', views.cause_detail, name='cause_detail'),
]

contact/urls.py
from django.urls import path
from .views import contact_view

app_name = 'contact'

urlpatterns = [
    path('', contact_view, name='contact'),
]

events/urls.py
from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [
    path('events/', views.event_list, name='event_list'),
    path('events/<slug:slug>/', views.event_detail, name='event_detail'),
]

insaniyatforgaza/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from .views import Home, service, team

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home, name='home'),
    path('service/', service, name='service'),
    path('team/', team, name='team'),
    path('about/', include('about.urls')),
    path('', include('causes.urls', namespace='causes')),
    path('', include('events.urls', namespace='events')),
    path('', include('blog.urls', namespace='blog')),
    path('contact/', include('contact.urls')),
    path('', include('volunteer.urls', namespace='volunteer')),
    path('boycott/', include('boycott.urls', namespace='boycott')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/footer.html
{% load static %}

<div class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-contact">
                            <h2>Our Head Office</h2>
                            <p><i class="fa fa-map-marker-alt"></i>123 Street Islamabad, Pakistan</p>
                            <p><i class="fa fa-phone-alt"></i>+092 345 67890</p>
                            <p><i class="fa fa-envelope"></i>insaniyatforgaza@gmail.com</p>
                            <div class="footer-social">
                                <a class="btn btn-custom" href=""><i class="fab fa-twitter"></i></a>
                                <a class="btn btn-custom" href=""><i class="fab fa-facebook-f"></i></a>
                                <a class="btn btn-custom" href=""><i class="fab fa-youtube"></i></a>
                                <a class="btn btn-custom" href=""><i class="fab fa-instagram"></i></a>
                                <a class="btn btn-custom" href=""><i class="fab fa-linkedin-in"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-link">
                            <h2>Popular Links</h2>
                            <a href="{% url 'about' %}">About Us</a>
                            <a href="{% url 'contact:contact' %}">Contact Us</a>
                            <a href="{% url 'causes:cause_list' %}">Popular Causes</a>
                            <a href="{% url 'events:event_list' %}">Upcoming Events</a>
                            <a href="{% url 'blog:blog_list' %}">Latest Blog</a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-link">
                            <h2>Useful Links</h2>
                            <a href="">Terms of use</a>
                            <a href="">Privacy policy</a>
                            <a href="">Cookies</a>
                            <a href="">Help</a>
                            <a href="">FQAs</a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-newsletter">
                            <h2>Newsletter</h2>
                            <form>
                                <input class="form-control" placeholder="Email goes here">
                                <button class="btn btn-custom">Submit</button>
                                <label>Don't worry, we don't spam!</label>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container copyright">
                <div class="row">
                    <div class="col-md-6">
                        <p>&copy; <a href="{% url 'about' %}">Insaniyat for Gaza</a>, All Right Reserved.</p>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->

        <!-- Back to top button -->
        <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

templates/includes/navbar.html
{% load static %}

   <div class="top-bar d-none d-md-block">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-8">
                        <div class="top-bar-left">
                            <div class="text">
                                <i class="fa fa-phone-alt"></i>
                                <p>+092 345 67890</p>
                            </div>
                            <div class="text">
                                <i class="fa fa-envelope"></i>
                                <p>insaniyatforgaza@gamil.com</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="top-bar-right">
                            <div class="social">
                                <a href=""><i class="fab fa-twitter"></i></a>
                                <a href=""><i class="fab fa-facebook-f"></i></a>
                                <a href=""><i class="fab fa-linkedin-in"></i></a>
                                <a href=""><i class="fab fa-instagram"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Top Bar End -->

        <!-- Nav Bar Start -->
        <div class="navbar navbar-expand-lg bg-dark navbar-dark">
            <div class="container-fluid">
                <a href="{% url 'home' %}" class="navbar-brand">IFG</a>
<span class="d-none d-md-inline">Insaniyat for Gaza</span>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav ml-auto">
                        <a href="{% url 'home' %}" class="nav-item nav-link active">Home</a>
                        <a href="{% url 'about' %}" class="nav-item nav-link">About</a>
                        <a href="{% url 'causes:cause_list' %}" class="nav-item nav-link">Causes</a>
                        <a href="{% url 'events:event_list' %}" class="nav-item nav-link">Events</a>
                        <a href="{% url 'blog:blog_list' %}" class="nav-item nav-link">Blog</a>
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Pages</a>
                            <div class="dropdown-menu">
                                <a href="{% url 'service' %}" class="dropdown-item">What We Do</a>
                                <a href="{% url 'team' %}" class="dropdown-item">Meet The Team</a>
                                <a href="donate.html" class="dropdown-item">Donate Now</a>
                                <a href="{% url 'volunteer:volunteer' %}" class="dropdown-item">Become A Volunteer</a>
                                <a href="{% url 'boycott:boycott-list' %}" class="dropdown-item">Boycott Hub</a>
                            </div>
                        </div>
                        <a href="{% url 'contact:contact' %}" class="nav-item nav-link">Contact</a>
                    </div>
                </div>
            </div>
        </div>